### ISSUE TITLE
Add accesskey A to menu item

### ISSUE THREAD

**Issue by hdhoang** [apiraino/link_cleaner#34]
G'day to you,

Since firefox 88, we no longer have accesskey A for item `Copy Link`, cf https://bugzilla.mozilla.org/show_bug.cgi?id=1701324. A [workaround web-ext](https://addons.mozilla.org/en-US/firefox/addon/copy-link-address-a/) is available too.

I suggest we use `Link-&Addresse` for Deustch, `cle&an` for English, and `Copi&a` for Italiano, to provide the same functionality.

What do you think?

**Comment by apiraino** [comment]
*sigh* ... again Mozilla doing its thing.

thanks @hdhoang for bringing this to my attention. I suppose we should add then in the `title` property of the [menus.create API](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/menus/create), if I'm not wrong.

If you have time to submit a patch for this, that will be greatly appreciated. Otherwise I'll circle back on this and do it myself (soon:tm:)

**Comment by hdhoang** [comment]
Thanks for the definitive API link, I'll add the ampersand to `menuItemCopyAndClean` for each locale. While at it, I'll also add some translations too!
