### ISSUE TITLE
Link Cleaner+ or ClearURL or URL cleaning list?

### ISSUE THREAD

**Issue by katastrophe92** [apiraino/link_cleaner#44]
Hello

too many alternatives to use 😂😂😂😂 
i tried all 3 and all worked well but do not know which one is the safest and do not need extra fiddling. 
What to use?

**Comment by apiraino** [comment]
Totally fair point.

Personally I use [ClearURL](https://docs.clearurls.xyz/1.26.1) since a long time because it has more filters and it is available in the Add-on Mozilla store for Firefox Android (without fiddling with custom addons collections).

"Link Cleaner+" was born from a fork of [Link Cleaner](https://github.com/idlewan/link_cleaner) at a time when there weren't better alternatives, but now I don't think it offers signficant advantages.

**Comment by NoXPhasma** [comment]
I've had massive issues with ClearUrls on many sites. Including Amazon, on which it prevented me from changing the sorting of the search entries. Your addon is actually the best I came across so far :)

**Comment by Korb** [comment]
> I've had massive issues with ClearUrls on many sites.

The functionality of domain exclusion lists [has not yet been added](https://github.com/ClearURLs/Addon/issues/93).
